version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: termdesk-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - termdesk-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: termdesk-backend
    ports:
      - "8001:8001"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - DB_NAME=termdesk_db
      - CORS_ORIGINS=http://localhost:3000
    depends_on:
      - mongodb
    networks:
      - termdesk-network
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: termdesk-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8001
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
    networks:
      - termdesk-network
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    restart: unless-stopped

networks:
  termdesk-network:
    driver: bridge

volumes:
  mongodb_data: